version: "3.9"

services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - DATABASE_URL=sqlite:///./mydatabase.db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  redis:
    image: redis:6
    ports:
      - "6379:6379"
