name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2️⃣ Set up Python (linting & tests)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 src/ || exit 0
       
    # 3️⃣ Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 4️⃣ Log in to GitHub Container Registry (GHCR)
    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 5️⃣ Build and Push Docker Image
    - name: Build and push Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/my-fastapi-app:latest
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME


    
