name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2️⃣ Set up Python (linting & tests)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 src/ || exit 0

    # 3️⃣ Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 4️⃣ Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 5️⃣ Build and Push Docker Image
    - name: Build and push Docker image
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/rag-retrieval-llm-scrolls-of-retrieval
        # Build image with both latest and commit SHA tags
        docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} .
        # Push the tags separately
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:${{ github.sha }}




    
